### ISSUE TITLE
`setVelocitiesToTemperature` throws `GIL` error

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-ml#31]
following [this conda installation](https://github.com/openmm/openmm-torch/issues/76) (i.e. `conda create -n tmp-test -q -c conda-forge openmm-torch nnpops torchani openmmtools cudatoolkit=11.3`) and adding a single line to `TestMLPoential.py` that looks like:

```
interpContext.setVelocitiesToTemperature(300*unit.kelvin)
```
passes the `assertAlmostEqual` but fails on the velocity setting with:

```
======================================================================
ERROR: testCreateMixedSystem (__main__.TestMLPotential)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lila/home/rufad/github/openmm-ml/test/TestMLPotential.py", line 33, in testCreateMixedSystem
    interpContext.setVelocitiesToTemperature(300*unit.kelvin)
  File "/home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/openmm.py", line 12141, in setVelocitiesToTemperature
    return _openmm.Context_setVelocitiesToTemperature(self, *args)
openmm.OpenMMException: The autograd engine was called while holding the GIL. If you are using the C++ API, the autograd engine is an expensive operation that does not require the GIL to be held so you should release it with 'pybind11::gil_scoped_release no_gil;'. If you are not using the C++ API, please report a bug to the pytorch team.
Exception raised from execute at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1650965732461/work/torch/csrc/autograd/python_engine.cpp:120 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x68 (0x2afa6d274a78 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xe8 (0x2afa6d251d6e in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0xb0 (0x2afac8327030 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x2c1db16 (0x2afa39749b16 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<bool>, bool, std::vector<at::Tensor, std::allocator<at::Tensor> > const&) + 0x69 (0x2afa3974a5d9 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x2c75fe1 (0x2afa397a1fe1 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: at::Tensor::_backward(c10::ArrayRef<at::Tensor>, c10::optional<at::Tensor> const&, c10::optional<bool>, bool) const + 0x49 (0x2afa378cdb69 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #7: TorchPlugin::ReferenceCalcTorchForceKernel::execute(OpenMM::ContextImpl&, bool, bool) + 0xdff (0x2afabef3828f in /home/rufad/miniconda3/envs/omm_dev2/lib/plugins/libOpenMMTorchReference.so)
frame #8: OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) + 0xc9 (0x2afa1ab310d9 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.7.7)
frame #9: OpenMM::ReferenceCustomCVForce::calculateIxn(OpenMM::ContextImpl&, std::vector<OpenMM::Vec3, std::allocator<OpenMM::Vec3> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > > const&, std::vector<OpenMM::Vec3, std::allocator<OpenMM::Vec3> >&, double*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, double> > >&) const + 0xde (0x2afa1ac3375e in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.7.7)
frame #10: OpenMM::ReferenceCalcCustomCVForceKernel::execute(OpenMM::ContextImpl&, OpenMM::ContextImpl&, bool, bool) + 0x302 (0x2afa1ac0c612 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.7.7)
frame #11: OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) + 0xc9 (0x2afa1ab310d9 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.7.7)
frame #12: OpenMM::Context::setVelocitiesToTemperature(double, int) + 0xd0 (0x2afa1ab2d990 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/../../../libOpenMM.so.7.7)
frame #13: <unknown function> + 0x118456 (0x2afa1a88e456 in /home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/_openmm.cpython-39-x86_64-linux-gnu.so)
<omitting python frames>


----------------------------------------------------------------------
Ran 1 test in 18.655s

FAILED (errors=1)
```

**Comment by peastman** [comment]
The fix is in https://github.com/openmm/openmm/pull/3424.  If you use a dev build of OpenMM it should work.
