### ISSUE TITLE
`TorchForce` inside `CustomCVForce` fails with `nnpops` implementation

### ISSUE THREAD

**Issue by dominicrufa** [openmm/openmm-ml#32]
I have been trying to create a minimally-modified implementation to get `nnpops` working on a conda-installable `openmm-ml` environment, and i am encountering an error in `TestMLPotential.py` with the implementation. 

If you drop in/replace the `anipotential.py` with [this](https://github.com/dominicrufa/openmm-ml/blob/main/openmmml/models/vanilla_nnpops_anipotential.py)  and run the test, (making sure to set the `platform` to `CUDA`), you should see that the test fails on [line 26](https://github.com/openmm/openmm-ml/blob/4a68b858544b391a274aa7f33606fb07fe131bcc/test/TestMLPotential.py#L26), 

```
======================================================================
ERROR: testCreateMixedSystem (__main__.TestMLPotential)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lila/home/rufad/github/openmm-ml/test/TestMLPotential.py", line 26, in testCreateMixedSystem
    interpEnergy1 = interpContext.getState(getEnergy=True).getPotentialEnergy().value_in_unit(unit.kilojoules_per_mole)
  File "/home/rufad/miniconda3/envs/omm_dev2/lib/python3.9/site-packages/openmm/openmm.py", line 12318, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
openmm.OpenMMException: Error invoking kernel: CUDA_ERROR_INVALID_HANDLE (400)
```

meaning that the `createMixedSystem(..., interpolate=False)` is compatible with `nnpops`, but `interpolate=True` is not. 
I have found a way around this (by taking the `TorchForce` out of the customCVForce and adding a `scale` parameter to the `ANIForce` manually), but I don't want to open a PR attempting to merge my modifications unless the compatibility issue with `nnpops` can't be fixed an easier way.

**Comment by dominicrufa** [comment]
@peastman , @raimis: turns out ^this is actually the crux of [this issue](https://github.com/openmm/openmm-ml/issues/25)

**Comment by dominicrufa** [comment]
in the interest of getting `openmm-ml` working with `nnpops`, i think the easiest thing would be to just extract the `TorchForce` from the customCV (as in my fork) and run with it until a more stable solution is found. is that agreeable?

**Comment by dominicrufa** [comment]
@peastman, have you found a stable workaround for this issue, or should we proceed with removing the `TorchForce` from the `CVForce`?

**Comment by dominicrufa** [comment]
tagging @jchodera

**Comment by jchodera** [comment]
@dominicrufa : Can you test the PR here?
https://github.com/openmm/openmm-torch/pull/78

**Comment by dominicrufa** [comment]
@peastman , I am unable to source install the PR and make it compatible with the rest of the `conda`-installed bits needed for the `nnpops` test. if you can source install it locally, can you run the test i mentioned at the top of this issue?

**Comment by peastman** [comment]
It runs without problem now.  It looks like that fixes it!

**Comment by dominicrufa** [comment]
@peastman , awesome! can you merge the PR and make it conda-installable? i can add a PR with the `nnpops` implementation for `anipotential.py` [here](https://github.com/dominicrufa/openmm-ml/blob/main/openmmml/models/anipotential.py) and modify the test to test for the `torchani` and `nnpops` implementation if you'd like.

**Comment by raimis** [comment]
@peastman could reopen this. I don't permissions.

**Comment by peastman** [comment]
I just added you as a maintainer.  You should have full permissions now.

**Comment by raimis** [comment]
@dominicrufa I can reproduce the issue and created a minimal test https://github.com/openmm/openmm-torch/pull/80/commits/63a49c170232531c12edf5db2d2f5255af1dfa6f.

**Comment by dominicrufa** [comment]
@raimis , great! let me know if/when i can conda-install the fix to write the `openmm-ml` tests.

**Comment by dominicrufa** [comment]
yes, this is fixed. closing
