### ISSUE TITLE
Incompatibility with MACE 0.3.4 in OpenMM-ML

### ISSUE THREAD

**Issue by lcdumort** [openmm/openmm-ml#84]
Dear OpenMM-ML developers,

I've been successfully using OpenMM-ML to utilize MACE potentials for molecular dynamics simulations with MACE versions 0.2.x. However, after upgrading MACE to version 0.3.4, I encountered the following traceback error when running the same code:
```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
/vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00003/vsc43640/micromamba/envs/mlp_env/lib/python3.10/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
Traceback (most recent call last):
  File "/dodrio/scratch/projects/2024_030/loic/MLP_HSIL/workflow/results/loop_0/s3_openmm_simulation/HSIL_2.2_2/MD_openmm.py", line 141, in <module>
    main()
  File "/dodrio/scratch/projects/2024_030/loic/MLP_HSIL/workflow/results/loop_0/s3_openmm_simulation/HSIL_2.2_2/MD_openmm.py", line 42, in main
    result = work(**kwargs)
  File "/dodrio/scratch/projects/2024_030/loic/MLP_HSIL/workflow/results/loop_0/s3_openmm_simulation/HSIL_2.2_2/MD_openmm.py", line 93, in work
    system = potential.createSystem(topology,
  File "/vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00003/vsc43640/micromamba/envs/mlp_env/lib/python3.10/site-packages/openmmml/mlpotential.py", line 189, in createSystem
    self._impl.addForces(topology, system, None, 0, **args)
  File "/vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00003/vsc43640/micromamba/envs/mlp_env/lib/python3.10/site-packages/openmmml/models/macepotential.py", line 404, in addForces
    force = openmmtorch.TorchForce(module)
  File "/vscmnt/gent_kyukon_data/_kyukon_data_gent/vo/000/gvo00003/vsc43640/micromamba/envs/mlp_env/lib/python3.10/site-packages/openmmtorch.py", line 70, in __init__
    _openmmtorch.TorchForce_swiginit(self, _openmmtorch.new_TorchForce(file))
TypeError: in method 'new_TorchForce', argument 1 of type 'std::string const &'
```
Training with MACE 0.3.4 works without issues, indicating the problem might be in OpenMM-ML.
Should I downgrade back to MACE 0.2.x, or is there a workaround to use the newer MACE version?

###  Current Environment:
    Python: 3.10
    OpenMM-ML: 1.2
    MACE: 0.3.4
    PyTorch: 1.13.1.post200

Please let me know if you need any more information or if there is a potential fix.

Thank you for your help.

Best regards,

**Comment by peastman** [comment]
Strange, I'm not sure what kind of change would have caused that.

The C++ TorchForce class has two constructors: one that takes a string containing a path to a file, and the other taking a `torch::jit::Module` object.  The Python wrapper is supposed to also accept both of those.  The thing is, the Python object for a compiled module is a `torch.jit.ScriptModule`, which needs to be converted to the proper C++ class.  So we define a pair of SWIG typemaps, one to check whether the argument is the proper type and one to do the conversion.  The first one is the relevant one here:

```c++
%typecheck(SWIG_TYPECHECK_POINTER) const torch::jit::Module& {
    py::object o = py::reinterpret_borrow<py::object>($input);
    py::handle ScriptModule = py::module::import("torch.jit").attr("ScriptModule");
    $1 = py::isinstance(o, ScriptModule);
}
```

But you're getting the error message

> TypeError: in method 'new_TorchForce', argument 1 of type 'std::string const &'

which suggests that `py::isinstance()` is returning false (saying the argument isn't a ScriptModule object), so SWIG tries to call the other constructor that takes a string instead.

But the value being passed was just compiled with `torch.jit.script()`:

https://github.com/openmm/openmm-ml/blob/2d0fcefdedd7060275c046d91d36a5b49e73fbcc/openmmml/models/macepotential.py#L400-L404

So how could it not be the right class?  And why would a change to the MACE version make any difference?

I'll see if I can reproduce it.  @sef43 @JMorado do you have any idea what might be causing it?

**Comment by peastman** [comment]
I just tested this using both MACE 0.3.4 and 0.3.6 (the latest version).  It successfully built the system in both cases.  No sign of the error shown above.

That was using PyTorch 2.3.1.  Perhaps the problem is related to the older version you're using?

**Comment by JMorado** [comment]
I've also tested with MACE 0.3.4-6, and everything seems to be working fine for me. I'm also using Python 2.3.1.

**Comment by lcdumort** [comment]
Thank you for the quick reply, and my apologies for the delay.

I have upgraded everything, including using PyTorch version 2.3.1. Now everything seems to be working, so it was probably an incompatibility with PyTorch 1.13.x.

**Comment by peastman** [comment]
Glad that fixed it.
